spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    platform: postgresql

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000
          lob:
            non_contextual_creation: true
        dialect: com.example.demo.util.postgres.dialect.CustomDialect
    generate-ddl: true


